# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(661, 551)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 10, 661, 541))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.img_frame = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.img_frame.setText("")
        self.img_frame.setObjectName("img_frame")
        self.verticalLayout_5.addWidget(self.img_frame)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.inputFileButton = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.inputFileButton.setObjectName("inputFileButton")
        self.verticalLayout_2.addWidget(self.inputFileButton)
        self.inputFileLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.inputFileLineEdit.setObjectName("inputFileLineEdit")
        self.verticalLayout_2.addWidget(self.inputFileLineEdit)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.img_btn01 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.img_btn01.setObjectName("img_btn01")
        self.verticalLayout_3.addWidget(self.img_btn01)
        self.img_btn02 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.img_btn02.setObjectName("img_btn02")
        self.verticalLayout_3.addWidget(self.img_btn02)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.computeMatch = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.computeMatch.setObjectName("computeMatch")
        self.verticalLayout_4.addWidget(self.computeMatch)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Matching Keypoint Descriptor"))
        self.inputFileButton.setText(_translate("Form", "..."))
        self.img_btn01.setText(_translate("Form", "image 1"))
        self.img_btn02.setText(_translate("Form", "image 2"))
        self.computeMatch.setText(_translate("Form", "compute"))
